export const GETALL_REQUERIMIENTOS ='GETALL_REQUERIMIENTOS';
export const ADD_REQUERIMIENTO ='ADD_REQUERIMIENTO';
export const UPDATE_REQUERIMIENTO ='UPDATE_REQUERIMIENTO';
export const REMOVE_REQUERIMIENTO ='REMOVE_REQUERIMIENTO';
export const FILTER ='FILTER';
export const ORDER ='ORDER';
export const ADD_ORDEN_SERVICIO = 'ADD_ORDEN_SERVICIO';